### ISSUE TITLE
So gif aren't supported ?

### ISSUE THREAD

**Issue by une-mouche** [MCharpy/bruce#2] opened 2022-05-30 21:03 UTC

**Comment by MCharpy** [comment] 2022-05-30 21:04
Closed for duplicate of #1

**Comment by une-mouche** [comment] 2022-05-30 21:04
![image](https://user-images.githubusercontent.com/35428767/171059027-ff249e6d-a352-4ad3-a232-3c673a05df04.gif)

That's good, who likes gif ?

**Closed by MCharpy** 2022-05-30 21:04 UTC
